# lab3/docker-compose.yml

services:
  db:
    image: postgres:16
    container_name: lab3_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: lab3db
    ports:
      - "5433:5432"
    volumes:
      - lab3_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: lab3_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/lab3db
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: lab3_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VITE_API_URL: /api
    ports:
      - "3001:3000"

  nginx:
    image: nginx:alpine
    container_name: lab3_nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  lab3_postgres_data:
